### ISSUE TITLE
windows  compile error with vs2022

### ISSUE THREAD

**Issue by chinaminiren** [ExplosionEngine/Explosion#271]
error message:
 
Common.vcxproj -> C:\Work\Explosion\build\Lib\Debug\Common.lib
  Common.Test.vcxproj -> C:\Work\Explosion\build\Dist\Debug\Engine\Binaries\Common.Test.exe
  Core.vcxproj -> C:\Work\Explosion\build\Dist\Debug\Engine\Binaries\Core.dll
  Core.Test.vcxproj -> C:\Work\Explosion\build\Dist\Debug\Engine\Binaries\Core.Test.exe
  Mirror.vcxproj -> C:\Work\Explosion\build\Dist\Debug\Engine\Binaries\Mirror.dll
  Mirror.Test.vcxproj -> C:\Work\Explosion\build\Dist\Debug\Engine\Binaries\Mirror.Test.exe
  MirrorTool.Static.vcxproj -> C:\Work\Explosion\build\Lib\Debug\MirrorTool.Static.lib
  MirrorTool.vcxproj -> C:\Work\Explosion\build\Dist\Debug\Engine\Binaries\MirrorTool.exe
  MirrorTool.Test.vcxproj -> C:\Work\Explosion\build\Dist\Debug\Engine\Binaries\MirrorTool.Test.exe
  RHI.vcxproj -> C:\Work\Explosion\build\Lib\Debug\RHI.lib
  RHI-DirectX12.vcxproj -> C:\Work\Explosion\build\Dist\Debug\Engine\Binaries\RHI-DirectX12.dll
  RHI-Dummy.vcxproj -> C:\Work\Explosion\build\Dist\Debug\Engine\Binaries\RHI-Dummy.dll
  RHI-Vulkan.vcxproj -> C:\Work\Explosion\build\Dist\Debug\Engine\Binaries\RHI-Vulkan.dll
  Render.vcxproj -> C:\Work\Explosion\build\Lib\Debug\Render.lib
  RHI-SSAO.vcxproj -> C:\Work\Explosion\build\Dist\Debug\Engine\Binaries\RHI-SSAO.exe
  RHI-TexSampling.vcxproj -> C:\Work\Explosion\build\Dist\Debug\Engine\Binaries\RHI-TexSampling.exe
  RHI-Triangle.vcxproj -> C:\Work\Explosion\build\Dist\Debug\Engine\Binaries\RHI-Triangle.exe
  Render.Test.vcxproj -> C:\Work\Explosion\build\Dist\Debug\Engine\Binaries\Render.Test.exe
  Rendering.vcxproj -> C:\Work\Explosion\build\Dist\Debug\Engine\Binaries\Rendering.dll
  Generating ../../../Generated/MirrorInfoSource/Runtime/ECS.generated.cpp
C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.37.32822\include\yvals_core.h(847,1): error G4
1C625DC: static assertion failed: Error in C++ Standard Library usage. [C:\Work\Explosion\build\Engine\Source\Runtime\R
untime.Generated.vcxproj]

C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(249,5): e
rror MSB8066: “C:\Work\Explosion\build\CMakeFiles\bcb1d8ac9c42fad46bfd0938ee19bd7b\ECS.generated.cpp.rule;C:\Work\Explo
sion\build\CMakeFiles\bcb1d8ac9c42fad46bfd0938ee19bd7b\RuntimeModule.generated.cpp.rule;C:\Work\Explosion\build\CMakeFi
les\bcb1d8ac9c42fad46bfd0938ee19bd7b\World.generated.cpp.rule;C:\Work\Explosion\build\CMakeFiles\31de34aa6404d2b06b99f2
02932168b6\Runtime.Generated.rule”的自定义生成已退出，代码为 1。 [C:\Work\Explosion\build\Engine\Source\Runtime\Runtime.Generated.vcx
proj]

**Comment by FlyAndNotDown** [comment]
I closed this issue, if there is any other problem, just reopen the issue again.
