### ISSUE TITLE
macOS下编译源码报错的问题

### ISSUE THREAD

**Issue by scyq** [ExplosionEngine/Explosion#66]
我设置好了Vulkan的环境变量，也可以验证Vulkan的正确安装。
但是在最后```cmake --build .```的步骤出现了如下错误，看上去是Vulkan的问题，不知道如何解决？是环境配置的问题吗？
![image](https://user-images.githubusercontent.com/45393064/118771896-a9113280-b8b5-11eb-888f-284006f236f8.png)

**Comment by FlyAndNotDown** [comment]
这里应该是笔误，改成 VK_SUCCESS 试试，我们开发都是使用 CLion + MacOS，按理说应该我们也会报才对 ... 不过归根到底，MacOS 门禁还是需要的，我们现在只配置了 Windows 和 Linux 的门禁，回头把 MacOS 的门禁加上 ~
