### ISSUE TITLE
能力提升

### ISSUE THREAD

**Issue by FlyAndNotDown** [ExplosionEngine/Explosion#8]
* 图形 API 学习
     * [OpenGL](https://learnopengl-cn.github.io/)
     * [Vulkan](https://vulkan-tutorial.com/Introduction)
 * 游戏编程基础知识
     * 如何使用游戏引擎开发游戏
         * [Unity](https://docs.unity.cn/cn/2021.1/Manual/UnityManual.html)
         * [Unreal](https://docs.unrealengine.com/en-US/index.html)
    * 游戏接口设计
        * GameObject
        * 下一代接口设计 [ECS](https://docs.unity3d.com/Packages/com.unity.entities@0.1/manual/index.html)
 * 编程语言与框架
     * C++ 11-20 标准
     * [C++ 模板编程](https://github.com/wuye9036/CppTemplateTutorial)
     * [Qt](https://github.com/wuye9036/CppTemplateTutorial)
     * [EnTT](https://github.com/skypjack/entt)
     * [TaskFlow](https://github.com/taskflow/taskflow)
     * [GLFW](https://github.com/glfw/glfw)
     * [GLM](https://github.com/g-truc/glm)
 * 源码阅读
     * [Unreal](https://docs.unrealengine.com/en-US/BlueprintAPI/Media/MediaPlayer/OpenSource/index.html)
 * 其他
     * 反射与游戏脚本
     * 序列化
     * 游戏内存管理
     * GC
 * 材质
     * [PBR](https://jerkwin.github.io/filamentcn/Filament.md.html)

**Comment by D0ub1ePieR** [comment]
牛！
